// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsCosting = {
  // Generation automatique depuis la structure de dossiers costing-docs/
  costingSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebarsCosting;
